---
- name: setup ubuntu based kube node
  hosts: master
  vars:
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go-1.6
  gather_facts: false
  tasks:
    - name: install apt packages
      apt: name={{ item }} state=present update_cache=true
      items:
        - init-system-helpers
        - golang-1.6
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: get the latest etcd
      command: go get -u {{ item }}
      items:
        - github.com/coreos/etcd/cmd/etcd
        - github.com/coreos/etcd/cmd/etcdctl
      environment:
        GOROOT: "{{ lookup('env', 'GOROOT') }}"
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
        PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"

    - name: install encription key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: true

    - name: add gce kubernetes list
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        regexp: '^deb http://apt.kubernetes.io/'
        line: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        create: true
      become: true

    - name: install kubernetes packages
      apt: name={{ item }} state=present upgrade=true update_cache=false
      items:
        - kubelet
        - kubeadm
        - kubernetes-cni
      become: true
