---
- name: setup ubuntu based kube node
  hosts: node
  gather_facts: true
  vars:
    k8s:
      token: ad5342.add6b659ba10fdc0
      apiserver: 10.0.0.12:6443
      cert_hash: sha256:3bd1b57e94eb2e43cd90d8c78b59589c4f9811d68434d0944053f54587169f2d
    travis_ci: false
  tasks:
    - name: check if the node is already joining the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: join the k8s cluster!
      command: |
        kubeadm join --token "{{ k8s.token }}" "{{ k8s.apiserver }}"
        --discovery-token-ca-cert-hash "{{ k8s.cert_hash }}"
      become: true
      when: kubelet_conf.stat.exists == false and ansible_distribution_version == "16.04"
