---
- name: setup ubuntu based kube node
  hosts: node
  gather_facts: true
  vars:
    token: "{{ hostvars[master]['cluster_token'] }}"
    server: "{{ hostvars[master]['cluster_apiserver'] }}"
    cert: "{{ hostvars[master]['cluster_cert_hash'] }}"
    travis_ci: false
  tasks:
    - name: check if the node is already joining the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet

    - name: join to the cluster!
      command: "kubeadm join --token {{ token }} {{ server }} --discovery-token-ca-cert-hash {{ cert }}"
      become: true
      when: kubelet.stat.exists == false and ansible_distribution_version == "16.04"
